### ISSUE TITLE
[Suggestion] Publishing mattermost circleci orbs in an automated fashion

### ISSUE THREAD

**Issue by RajatVaryani** [mattermost/circleci-orbs#8]
Working on https://github.com/mattermost/mattermost-server/issues/13587 I released that we can automate the publishing of orbs to the namespace. The pipeline will involve sanity checks and publishing the orbs. 

I can help contribute to it. 

Reference links: [link](https://circleci.com/blog/creating-automated-build-test-and-deploy-workflows-for-orbs-part-2/)

**Comment by RajatVaryani** [comment]
@hanzei Can you please have someone look at this?

**Comment by hanzei** [comment]
I definitely see the need for making the release process for the Orb easier. But I'm concerned that auto releasing can lead to breaking build for plugins using the CI. E.g. the JIRA plugin uses always the latest release. Is there a way to avoid breaking builds by accident? Would git tags help?

cc @jaydeland
